### ISSUE TITLE
CAPS only coloring

### ISSUE THREAD

**Issue by oirfeodent** [Ekopalypse/EnhanceAnyLexer#1]
Using the below in EnhanceAnyLexerConfig.ini file, also highlights small letter words.
Is this by intention, if so what should be done to color only words with CAPS only.
0xff00ff = \b([A-Z]+)\b

**Comment by Ekopalypse** [comment]
The default setting in Npp is that it is not case sensitive, you must specify this explicitly with a (?-i), i.e.
`0xff00ff = (?-i)\b([A-Z]+)\b`

**Comment by oirfeodent** [comment]
Thx @Ekopalypse .
Its not an issue then, will close it.
