### ISSUE TITLE
Case sensitive regexes

### ISSUE THREAD

**Issue by XiaoP76** [Ekopalypse/EnhanceAnyLexer#13]
Hi Ekopalypse,

I have a regex
`0xFF6000 = (QUEUED|CANCELED)`
which highlights both `QUEUED` and `queued`.
Is there a possibility to make the regex case sensitive ?

Best regards

XiaoP76

**Comment by Ekopalypse** [comment]
Hi @XiaoP76, thank you for your interest in the plugin.
With the [pattern modifiers](https://npp-user-manual.org/docs/searching/#search-modifiers) you can control the case sensitivity. 
In your case, a regex like `(?-i)QUEUED` should do what you are looking for.

Best regards

**Comment by XiaoP76** [comment]
Thanks, worked like a charm !
