### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by pryrt** [Ekopalypse/EnhanceAnyLexer#2]
I just downloaded v.1.0.0.  

My debug info confirms
```
Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : C:\usr\local\apps\notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 20H2
OS Build : 19042.1586
Current ANSI codepage : 1252
Plugins : 
...
    EnhanceAnyLexer (1)
...
```
but the About box still says v0.4.0
![image](https://user-images.githubusercontent.com/17455758/183668209-57c46348-4dd2-4849-8320-11c945adbc0a.png)

Is there a way to tie those two, so the [About box](https://github.com/Ekopalypse/EnhanceAnyLexer/blob/f64735b7cfbb081f0e23ecc2e81fa8a2e54536f3/enhance_any_lexer.v#L213) always grabs the [same version](https://github.com/Ekopalypse/EnhanceAnyLexer/blob/main/enhance_any_lexer.rc) that the plugin reports to Notepad++?  Because having two different sources for the version number virtually guarantees you'll get out of sync like this.

**Comment by Ekopalypse** [comment]
Yes, I overlooked that ... I'm not sure if there is currently a way to assign a common constant for V-sources and C-sources and possibly also for ReadMe.md. I'll have to think about it. Maybe I'll just use a UNIQUE string and replace it before publishing everything to Github, and then undo it.

**Comment by pryrt** [comment]
When I am developing perl modules, I often have my version number in one file, and then I have my make/build/equivalent propagate that version to all the appropriate places before doing a compile or bundle or equivalent step.

**Comment by Ekopalypse** [comment]
Fixed with https://github.com/Ekopalypse/EnhanceAnyLexer/commit/bb0c8a835bff90ee6351e3ae6f9fe243571502cc
