### ISSUE TITLE
styleid reference for excluded_styles for UDL

### ISSUE THREAD

**Issue by pryrt** [Ekopalypse/EnhanceAnyLexer#3]
in the [config-file `initialize()` function](https://github.com/Ekopalypse/EnhanceAnyLexer/blob/f64735b7cfbb081f0e23ecc2e81fa8a2e54536f3/notification_handler.v#L125-L128), the comments tell the user where to find the StyleID numbers in stylers.xml... which is great for a normal lexer.  But for UDL, the StyleID are not found in stylers.xml or equivalent.  Maybe add a line that says,

> ; For a UDL, look at the SCE_USER_STYLE_... constants in https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/lexilla/include/SciLexer.h to see which UDL field each styleID lines up with

**Comment by Ekopalypse** [comment]
For udl, the corresponding style xml would be userDefineLang.xml, right?
But I have to admit that I'm still having trouble understanding when a UDL is added to the userDefineLang.xml and when it is a separate XYZ.xml in the ...\Npp\userDefineLangs directory.

**Comment by Ekopalypse** [comment]
I think I understand what you mean. Unlike the stylers.xml, the style IDs in a UDL are only visible in the delimiter section and not in the corresponding WordStyle sections.

**Comment by pryrt** [comment]
> style IDs in a UDL are only visible in the delimiter section

If you mean, 

> ```<Keywords name="Delimiters">00&quot; 01 02&quot; 03$( 04 05) 06:: 07 08((EOL)) 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23</Keywords>```

then it's worse than you describe.  Those integers refer to the 8x3=24 boxes in the 8 delimiter styles -- 0-2 are DELIMITER1 STYLE, etc.  So they don't correspond directly to a styleID either.  The styleIDs for delimiter1 thru delimiter8 are 16-23.

...
Regarding practicalities of the link in the comments:

I'm not sure which is better to link to for SciLexer.h link: the generic master blob (https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/lexilla/include/SciLexer.h) and asking them to search for the constants (as I originally suggested); or the line numbers in the current master blob (https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/lexilla/include/SciLexer.h#L209-L235) hoping the line numbers don't change; or the line numbers in a specific commit (https://github.com/notepad-plus-plus/notepad-plus-plus/blob/a61b03ea8887e21c6e1b7374068962f635b79b80/lexilla/include/SciLexer.h#L209-L235) knowing that the link will always be right, but the version of the SciLexer.h it points to will be to an old version the next time that include file changes.

**Comment by Ekopalypse** [comment]
You are right. These IDs have nothing to do with styles.
I'm not sure which source to point to either.
I guess I will go with this one

~~~ini
; The optional line of excluded_styles is expected in the form of
; excluded_styles = 1,2,3,4,5 ...
; The numbers refer to the style IDs used by the lexer and
; can be taken from the file stylers.xml or USED_THEME_NAME.xml
; and in case of UDLs the mapping is only described in the source code
; https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/lexilla/include/SciLexer.h
; starting from SCE_USER_STYLE_DEFAULT
~~~

By the way ... thank you for your help and attention.

**Comment by Ekopalypse** [comment]
Fixed with https://github.com/Ekopalypse/EnhanceAnyLexer/commit/bb0c8a835bff90ee6351e3ae6f9fe243571502cc
