### ISSUE TITLE
lines without color in batch file

### ISSUE THREAD

**Issue by amymor** [Ekopalypse/EnhanceAnyLexer#5]
hello, thank you for such a great plugin.
but it seems cant color all lines (only a limited amount), here is my settings to colorize lines that start with `echo` in batch files:
```
[batch]
0x66BF93 = (?-s)^echo\C.*
```
and here is example of my problem:
https://imgur.com/YKvriTA.png

is there another way to color all lines that start with `echo` in NPP?

**Comment by Ekopalypse** [comment]
Thank you for your interest in this plugin.
I think I see what the problem is, you are using the word wrap feature, if you disable it I assume it will work then, correct?
Nonetheless, this needs to be addressed as it seems it has the potential to leave Npp hanging.

**Comment by Ekopalypse** [comment]
Can you try the [latest version](https://github.com/Ekopalypse/EnhanceAnyLexer/releases) a try?
I can't exactly reproduce your problem, mine looks a little different. If the problem still exists with the latest version, would it be possible to get a test file that causes this problem and the complete contents of the EnhanceAnyLexer configuration file?
![image](https://user-images.githubusercontent.com/47723516/184584553-90335df6-78cb-41c9-ae8a-586b2978a28c.png)

**Comment by amymor** [comment]
thank you for your response
yes i didnt see any problem while word wrap disabled, but i need word wrap. also i noticed that when i press Ctrl+R, the lines become colored, but when i scroll down, the problem occurs again.

**Comment by Ekopalypse** [comment]
What does the Ctrl+R do in your case? Does it reload the file?

**Comment by amymor** [comment]
i tried it, still same problem.
here is my complete settings:
```
[global]
indicator_id=0
debug_mode=0
offset=0
offset=0[batch]
0x66BF93 = (?-s)^echo\C.*
```
also i noticed that color is only applied once when i vertically scrolled or typed/deleted something, so if i open a small file(without vertical scrollbar) the color not applied at strat:
https://imgur.com/4r63vNj.gif

**Comment by amymor** [comment]
> What does the Ctrl+R do in your case? Does it reload the file?

yes

**Comment by Ekopalypse** [comment]
Thanks for the take - I see what you mean. 
I will try to fix it today after the "real" work. ;-)

**Comment by amymor** [comment]
thank you very much

**Comment by Ekopalypse** [comment]
Can you give [this version](https://github.com/Ekopalypse/EnhanceAnyLexer/releases/tag/v.1.1.2) a try?

**Comment by amymor** [comment]
thank you, it solved coloring at srartup , but still main problem exists when word wrap is enable.

**Comment by Ekopalypse** [comment]
Are we still talking about the exact same word-wrap issue? The only problem I see at the moment is that when using word-wrap, when you resize the window, the content is not updated until you click back in.

**Comment by amymor** [comment]
by the main problem, i mean the first problem that i mentioned in the first comment:
https://imgur.com/bH9CLNE.gif

**Comment by Ekopalypse** [comment]
I agree, there is definitely something still wrong.

**Comment by Ekopalypse** [comment]
I've created an [experimental version](https://github.com/Ekopalypse/EnhanceAnyLexer/releases/tag/v1.1.3) that should solve the problem, but I am not sure if I want to keep it. I need to test this with my workflow to see if there are performance issues.

**Comment by amymor** [comment]
> I've created an [experimental version](https://github.com/Ekopalypse/EnhanceAnyLexer/releases/tag/v1.1.3) that should solve the problem, but I am not sure if I want to keep it. I need to test this with my workflow to see if there are performance issues.

thank you very much❤️
it worked fine. i also created a batch file with 100,000 line and tested it while plugin was enabled, then disabled plugin and tested that batch file again, didnt notice any difference in terms of performance and memory usage.

**Comment by Ekopalypse** [comment]
Thank you very much for the test. Yes, it seems, at least with my workflow, that the effects are not as bad as I feared. If someone uses a lot of folded lines, the effects are more noticeable, but that's a problem that can occur anyway and can't really be solved with the current way of determining matches.

**Comment by Ekopalypse** [comment]
No problems\delays had occurred since the calculation of the visual area was expanded, so this calculation will be retained.
