### ISSUE TITLE
change manually enhanceanylexerconfig.ini doesnt update variables colors

### ISSUE THREAD

**Issue by txotelusco** [Ekopalypse/EnhanceAnyLexer#9]
Hi @Ekopalypse .
First, thanks for this contribution. I recently found on the notepad++ forum about, and it works so good for more complex color configuration.
I am a CNC programmer, to far from real programing. CNC are really more basics.
With your plugging I almost finished to create my own language for CNC programs. There is only one thing I more or less finised but I don’t know why it doesn’t work as I expected.
Basically I would like to color the local variable of programs. All CNC usually need to define at the beginning of program.
I am able by regex to find the particular word I want by using for example : 0xFF7700 = (?-s)^\h*(def real) \K.*$. On program like this.

REF REAL DIAM
….
DIAM=25

Then I can highlight the definition, but it doesn’t work for the same words in the program.
So, I thought that maybe I can do something like that.
localVar: (?-s)^\h*(def real) \K.*$
0xFF7700 = localVar
But It doesn’t work.
So, I decided to create my own scrip with python and then open a file, read, get the local var, copy on a string like:
0xFF7700 = (DEF1|DEF2|DEF3|....)
This part works, and finally I open the enhanceanylexerconfig.ini and paste this new line all with the same script. 
I check the file is ok, but my surprise is that finally it doesn’t work. I have to click on plugins, enhance current language, just write an space or intro, save, and then the color works. Seems that when I modified the ini file doesn’t have any effect. Only open by notepad buttons works and save works.
Is there any way to update by python scripts?
Regards¡

**Comment by txotelusco** [comment]
Hi Ekopalyse.
Wow, I didn’t know if you Will receive my question.
Thanks for the quickly reply¡
For me, If the idea about creates localvar to save and use it like in the example will be enough.
I work basically with Siemens CNC. CNC environment is too much easy in terms of programing and also programs normally are short(About 300 lines or less). One full machine backup is about (programs, global var, tables.etc) is normally about 1Mb to have an idea. So computationally resources is not a problem (I think).
Until last week I was using just User defined language, But there was some particular things that it was impossible. Like highlight words ended by “:” jump labels, etc, finally I learn about this plugin and then all is possible. So I started to think about more and more options like the local var I told you.
The idea about do something like “(?-s)^\h*(def real) \K.*$” seens to be ok, But on the definitions of local variables you ca do something like this,
***********************
DEF BOOL DEBUG=FALSE ; localvar with initialization
DEF REAL W_2=90 , W_22  ; localvar x2or more in one line
DEF REAL W_3=180
DEF REAL Setval__1[3]  , Setval__2[3]  ; array of variables
DEF REAL TcD__1[3,3] ; array of variables bidimensional
DEF REAL WzOv[3] 
DEF REAL WzRv[3]
***********************
Yesterday I create a python scrip to make a read about the file and generate the structure to copy at the end of the 
Ini file. So with the Scrip I finally (thanks to google and forums) get the exact result no matter “[]”, number of var, etc.
I went deeper…lol.. I make the scrip goes into the folder of Global variables(GUDs) and scan also for that ones. The time in my computer is milliseconds. And probably my programing is totally a mess.
Finally, I create this ini file and for me is so good. The only problem until this point is that I need to click on plugins->enhanced and insert an space or something. Because even if I open with note pad, but open it from the folder /appdata/roaming… It doesn’t work. I need to open the file by notepad buttons.
So as you said, maybe has the option to include on the scrip a way to re-read by the plugin will be a good idea. But, I read about what you said NPPM_MSGTOPLUGIN, but I didn’t understand anything…

I give you an example about the final ini file I am using.
THANKS¡¡¡

***********************
[cnc_extended_v2]

; check in the respective styler xml if the following IDs are valid
excluded_styles = 1,2,3,5,6,8,9,10,11,12,13,14,15,16,20,21,22,23
; IDS quitadas, 4:Comentarios 7 numeros
;;*******Palabras acabadas en ":"
0xff33ff =^((?!MSG;?).)*?:
;*******GOTO[BFs] marca siguiente palabra*******
0xff33ff = (?<=GOTO[BF] )\w+
; F Comandos marcados
0xEE8F82 =F\d+.?\d+
0xEE8F82 =F=\w+
0xEE8F82 =F\d+
;Rs
#EE8F82 =R\d+
;Ms
#7fff00 =M\d+
;Nlinea
0x9b9b9b =N\d+

0xaaeeaa=(DEBUG|F_S|_TNO|_MTH|W_1|W_2|W_3|W_4|M_T|R_ADIUS|KR|SETVAL__1|TCD__1)
;update local var finished
0xffffbb=(_RENT|PACHI|RUKI|_RENT|_RENC|AXV|XFRM_IDEAL_PT) ; real one has 3000 caracters 😊
;update GUDs finished
***********************

**Comment by Ekopalypse** [comment]
Hi @txotelusco,

What version of enhanceanylexer are you using, saving the ini works for me as seen in the attached gif.
As for the msgtoplugin feature, it works as also seen in the gif.
I used two npp instances to show that the ini file was modified from another source. However, your python script must be called from the npp instance that hosts the actual CNC file. I will use the new version today and, if nothing unusual turns up, release a draft version tomorrow for you to test. Does what is shown make sense from your point of view?

![enhance_any_lexer_msgtoplugin_demo](https://github.com/Ekopalypse/EnhanceAnyLexer/assets/47723516/5b28c5c3-7980-4ea5-aaa0-b282a8f327b8)

**Comment by txotelusco** [comment]
Hi @***@***.***>
My versión of enhanceanylexer is:
***@***.***
Y versión of Notepad++ is:
***@***.***

I sent you attached the las ini file I am using (rename the file extensión aaa to ini)

Looks so Good. What I have now implemented is like this:

  *   I have a copy of your original EnhanceAnyLexerConfig.ini file on another folder.
  *   Then execute the Python on by a button on the Notepad (the CNC file has to be selected).
     *   first remove the EnhanceAnyLexerConfig.ini file storage in appdata/plugings/…
     *   Read the file (editor.forEachLine) in order to get values of local Var and create finally in another temp file all in one line something like: 0xccffcc=(KATANJA|TANKATIA|TOOL_X|TOOL_Y|TOOL_Z|SPEED|BASE_NUMBER|)
     *   Then copy the EnhanceAnyLexerConfig.ini at my temp folder to plugins folder
     *   Open the EnhanceAnyLexerConfig.ini file and paste the local var at the end.
At this point, for me is OK, I know that I just need to open the file by notepad and just insert something, save, and the colors are ready.
So, If I can be able to add something at the end of the scrip to execute re-read function will be perfect. (Later I would like to do it automatically whenever a CNC file is opened, but for next chapter. LOL)

I was boring, and finally yesterday I made something else. Normally backups has the same structure.

  *   NC All backup inside this folder
     *   CMA : Manufacturer programs.
     *   DEF : Inside there are the Global variables.
So, I create at the end of the scrip, a new search in order to find the DEF folder open all files an create in a second tempfile the global vars. And before paste at the end.
So now I can see when I executed the scrip the Global and local var in different colors.
The second part is because all these is new, and I just wanted to learn more about python.
And Probably today, I will make the next step, search at CMA folder the “names of programs” and create new color structure with programs names... The way a CNC call subprograms is just typing the name of the file.


***@***.***

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: ***@***.***>
Enviado: jueves, 5 de octubre de 2023 14:35
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [Ekopalypse/EnhanceAnyLexer] change manually enhanceanylexerconfig.ini doesnt update variables colors (Issue #9)


Hi @txotelusco<https://github.com/txotelusco>,

What version of enhanceanylexer are you using, saving the ini works for me as seen in the attached gif.
As for the msgtoplugin feature, it works as also seen in the gif.
I used two npp instances to show that the ini file was modified from another source. However, your python script must be called from the npp instance that hosts the actual CNC file. I will use the new version today and, if nothing unusual turns up, release a draft version tomorrow for you to test. Does what is shown make sense from your point of view?

[enhance_any_lexer_msgtoplugin_demo]<https://user-images.githubusercontent.com/47723516/272903370-5b28c5c3-7980-4ea5-aaa0-b282a8f327b8.gif>

**Comment by txotelusco** [comment]
Hi @***@***.***>
I attached the file, maybe the system reject attached files. I send you again.
I Add the tow Python script, one is to create ini file, and I made another one to restore original values. Remember that I am new at this kind of programs, many of the scripts are directly copy and probably could be improve a lot. Anyway, even like that it cost only less than 1sec to create the new ini, and for me is enough.
Also is attached a part of backup of a machine. Its with the one I made all test.
I am going to try now your new plugin¡¡¡
Regards¡


Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: ***@***.***>
Enviado: viernes, 6 de octubre de 2023 11:31
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [Ekopalypse/EnhanceAnyLexer] change manually enhanceanylexerconfig.ini doesnt update variables colors (Issue #9)


@txotelusco<https://github.com/txotelusco> - I do not see any attached files.
The pre-release version along with an example of how PythonScript can force the plugin to re-read its configuration file is available here<https://github.com/Ekopalypse/EnhanceAnyLexer/releases/tag/v.1.3.0>

**Comment by txotelusco** [comment]
Hi Ekopalypse, soory but I couldnt check the update. If I understood, I have to download de the dll and replace on the pluggins folder. but on this step my antivus block the file and I have no options to enable onthat computer.
Regards¡

**Comment by txotelusco** [comment]
Hi, When I installed the first time the anylexer was the version 1.1. When you told me to update, I checked on the Notepad that there was the 1.2 able to update. I updated without problems. But for the 1.3 I tried downloading the dll. But I can’t use this dll, antivirus block every time. And I can’t disable the antivirus.
Looks like, that from notepad updating there is not problems.
regards¡

**Comment by txotelusco** [comment]
Hi @Ekopalypse 
Finally, I find the way to install the new Dll. Its perfect¡ Works so good¡¡
thanks so much for your help¡¡
I would like to ask another question that probably you will know. It is possible to run the scripts automatically whenever a file (with particular extension, like *.spf or mpf) is open with notepad++? Right now, I put a button and then run the scrip and when it finish the colors change. But it will be better if I can run the script in the background when the file is opened.
Regards¡

**Comment by Ekopalypse** [comment]
Thx for letting me know. The new version will be automatically available starting from the next release of Npp aka. > 8.5.8.

> run the scripts automatically whenever a file
Yes, this is possible, but you have to make sure that certain settings are set.

1. change the startup behavior of PythonScript via `Plugin->PythonScript->Configuration...`, make sure `Initialization` is set to `ATSTARTUP` instead of `LAZY`.

![image](https://github.com/Ekopalypse/EnhanceAnyLexer/assets/47723516/b135748c-c874-484d-9cd1-a44c29b52bea)

2. create a new script and name it "startup.py".
It MUST be named startup.py. DO NOT USE the existing one.

![image](https://github.com/Ekopalypse/EnhanceAnyLexer/assets/47723516/fdc71699-0885-46c8-94e2-2323b3fbe6e9)

Note, that it MUST be in `User Scripts`

and you should see the following in the `plugin->python script->scripts` menu

![image](https://github.com/Ekopalypse/EnhanceAnyLexer/assets/47723516/ce4ec117-05b6-4358-bd74-330467000359)

3. Copy the following code into the newly created startup.py script and save it.

```py
from Npp import notepad, NOTIFICATION, console

console.show()

def on_file_open(args):
    print(notepad.getCurrentFilename())
    
notepad.callback(on_file_open, [NOTIFICATION.FILEOPENED])
```

Now check if it works by right-clicking the startup.py tab to open the context menu and click "Open in new instance".

![image](https://github.com/Ekopalypse/EnhanceAnyLexer/assets/47723516/cbdc4471-094f-48de-9f3a-e0e051d1a724)

A new NPP instance, with startup.py open, should open and the PythonScript console should open automatically.  Now open any file in this instance and you should automatically see the path name of this file printed in the console. If this is the case, the rest is now a question of what exactly should happen and what the actual script that should be used looks like.
